name: semver_tool
description: >
  Command line utility to help manage semantic versions.

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  version:
  args:
  meta:

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0

executables:
  semver: semver

publish_to: none
